using LanguageExt;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using static LanguageExt.Prelude;

namespace SpellTomeRemoverNG;

public class Program
{
    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings(
                nickname: "Settings",
                path: "settings.json",
                out Patcher.Settings
            )
            .SetTypicalOpen(GameRelease.SkyrimSE, "SpellTomeRemoverNG.esp")
            .Run(args);
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        Patcher patcher = new(state, new ConsolePatcherLogger());
        patcher.Run();
    }
}