using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace SpellTomeRemoverNG;

public class Program
{
    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings(
                nickname: "Settings",
                path: "settings.json",
                out Settings.Instance)
            .SetTypicalOpen(GameRelease.SkyrimSE, "SpellTomeRemoverNG.esp")
            .Run(args);
    }

    /// <summary>
    /// Runs the patcher to remove spell tomes from a Skyrim load order.
    /// </summary>
    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        Patcher patcher = new(state, IPatcherLogger.Create());
        patcher.Run();
    }
}